@FinanceApi_HostAddress = http://localhost:5175/api/
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpvYW9AZW1haWwuY29tIiwiaWQiOiI4MWFhNGRkOC1lM2I2LTQ2MmEtYTU0ZC05M2Y5YTc3NmQ3NzAiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc3MDUwNDE4OSwiZXhwIjoxNzcwNTExMzg5LCJpYXQiOjE3NzA1MDQxODl9.zp5IV3ojBiysgIatIlwtb5C1cT-GOQgmO8oLhSu3l6c
GET {{FinanceApi_HostAddress}}users
Accept: application/json

###

GET {{FinanceApi_HostAddress}}users/3a2ab1ed-16d9-497c-a4e5-5e084da1a97f
Accept: application/json

###

POST {{FinanceApi_HostAddress}}users
Content-Type: application/json

{
  "name": "João",
  "email": "joao@email.com",
  "phone": "12394193847",
  "password": "joao123"
}

###

DELETE {{FinanceApi_HostAddress}}users/
Accept: application/json

###

POST {{FinanceApi_HostAddress}}auth/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "password": "joao123"
}

###

GET {{FinanceApi_HostAddress}}accounts
Accept: application/json
Authorization: Bearer {{Token}}

###

POST {{FinanceApi_HostAddress}}accounts
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "userId": "81aa4dd8-e3b6-462a-a54d-93f9a776d770",
  "name": "Banco do Brasil",
  "description": "Conta do joão"
}

###

POST {{FinanceApi_HostAddress}}admin/users/3A2AB1ED-16D9-497C-A4E5-5E084DA1A97F/promote
Authorization: Bearer {{Token}}
