@LedgerCore_HostAddress = http://localhost:5175/api/
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imx1Y2NhZnJiekBnbWFpbC5jb20iLCJpZCI6IjNhMmFiMWVkLTE2ZDktNDk3Yy1hNGU1LTVlMDg0ZGExYTk3ZiIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTc3MDUxMzYzMywiZXhwIjoxNzcwNTIwODMzLCJpYXQiOjE3NzA1MTM2MzN9.fZkuyPWCoS5uQiPaKczH6-xDGb_dFDOs2aUxj3Nrdus



GET {{LedgerCore_HostAddress}}transactions
Authorization: Bearer {{Token}}

###

POST {{LedgerCore_HostAddress}}transactions
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "accountId": "c889d621-b7e4-47f6-bdea-d0f64b374299",
  "value": 4500,
  "name": "Salário",
  "description": "Salário mensal Umbler",
  "type": 1,
  "competenceDate": "2026-02-08T00:36:42.896Z",
  "settlementDate": "2026-02-08T00:36:42.896Z"
}